(* Forsyth-Edwards Notation *)
   FEN = PIECE-PLACEMENT <SPACE>
         SIDE-TO-MOVE <SPACE>
         CASTLING <SPACE>
         EN-PASSANT <SPACE>
         HALFMOVE-CLOCK <SPACE>
         FULLMOVE-COUNTER
   SPACE = ' '
   
   (* Piece Placement *)
   PIECE-PLACEMENT = RANK <SEP> RANK <SEP> RANK <SEP> RANK <SEP>
                     RANK <SEP> RANK <SEP> RANK <SEP> RANK
   <SEP> = '/'
   RANK = (DIGIT17? PIECE (DIGIT17? PIECE)* DIGIT17?) | '8'
   <DIGIT17> = #'[1-7]'
   <PIECE> = WHITE-PIECE | BLACK-PIECE
   <WHITE-PIECE> = 'P' | 'N' | 'B' | 'R' | 'Q' | 'K'
   <BLACK-PIECE> = 'p' | 'n' | 'b' | 'r' | 'q' | 'k'

   (* Side to Move *)
   SIDE-TO-MOVE = 'w' | 'b'

   (* Castling Ability *)
   CASTLING = '-' | 'K'? 'Q'? 'k'? 'q'?

   (* En Passant Target Square *)
   EN-PASSANT = '-' | SQUARE
   SQUARE = ('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h') ('3' | '6')

   (* Halfmove Clock *)
   HALFMOVE-CLOCK = #'[0-9]' #'[1-9]'*

   (* Fullmove Counter *)
   FULLMOVE-COUNTER = #'[1-9]' #'[0-9]'*
